# Generated by Django 5.2.5 on 2025-08-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('league_table_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('badge_url', models.URLField(blank=True, max_length=500, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='fixtures.division')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_league_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('away_league_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('decision', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Played', 'Played'), ('Walkover', 'Walkover'), ('Postponed', 'Postponed'), ('Bye', 'Bye')], default='Scheduled', max_length=20)),
                ('scorers_text', models.TextField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='fixtures.division')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='fixtures.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='fixtures.team')),
            ],
            options={
                'ordering': ['match_date', 'division__name'],
                'unique_together': {('home_team', 'away_team', 'match_date')},
            },
        ),
    ]
