# Generated by Django 5.2.5 on 2025-08-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='fixtures.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='fixtures.player')),
            ],
            options={
                'unique_together': {('player', 'fixture')},
            },
        ),
    ]
